package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.AuthBankDo;

public interface AuthBankMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AUTH_BANK
     *
     * @mbg.generated
     */
    int insert(AuthBankDo record);
}