package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.AuthOrgDo;

public interface AuthOrgMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AUTH_ORG
     *
     * @param authOrgDo 企业信息
     */
    int insert(AuthOrgDo authOrgDo);
}