package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.AuthPersonDo;

public interface AuthPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AUTH_PERSON
     *
     * @mbg.generated
     */
    AuthPersonDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AUTH_PERSON
     *
     * @mbg.generated
     */
    int insert(AuthPersonDo record);
}