package com.baofu.international.global.account.core.dal.mapper;


import com.baofu.international.global.account.core.dal.model.ExchangeRateDo;

public interface ExchangeRateMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXCHANGE_RATE
     *
     * @mbg.generated
     */
    ExchangeRateDo selectRateInfo(ExchangeRateDo exchangeRateDo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXCHANGE_RATE
     *
     * @mbg.generated
     */
    int insert(ExchangeRateDo exchangeRateDo);

    /**
     * 更新汇率
     *
     * @param exchangeRateDo 平台流水号
     * @return 影响条数
     */
    int updateExchangeRate(ExchangeRateDo exchangeRateDo);
}