package com.baofu.international.global.account.core.dal.mapper;


import com.baofu.international.global.account.core.dal.model.ExternalOrderItemDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExternalOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_ORDER_ITEM
     *
     * @mbg.generated
     */
    ExternalOrderItemDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_ORDER_ITEM
     *
     * @mbg.generated
     */
    int insert(ExternalOrderItemDo record);

    /**
     * 查询指定OrderId的订单明细
     *
     * @param detailsOrderIds 订单明细编号
     * @return List<FiCbPaySettleOrderDo>  批次文件明细
     */
    List<ExternalOrderItemDo> selectByOrderId(@Param("detailsOrderIds") List<Long> detailsOrderIds);
}