package com.baofu.international.global.account.core.dal.mapper;


import com.baofu.international.global.account.core.dal.model.ExternalOrderDo;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface ExternalOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_ORDER
     *
     * @mbg.generated
     */
    ExternalOrderDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_ORDER
     *
     * @mbg.generated
     */
    int insert(ExternalOrderDo record);

    /**
     * 查询可用订单信息
     *
     * @param externalOrderDo 查询条件
     * @return List<ExternalOrderDo>  订单信息
     */
    List<ExternalOrderDo> queryExternalOrderInfo(ExternalOrderDo externalOrderDo);

    /**
     * 根据订单号批量修改订单的使用状态
     *
     * @param orderId  请求参数
     * @param state    订单使用状态
     * @param sellerId 卖家编号
     * @return 影响行数
     */
    int batchUpdateExternalOrderState(@Param("orderIdList") List<Long> orderId,
                                      @Param("state") Integer state,
                                      @Param("sellerId") String sellerId);

    /**
     * 查询指定OrderId的订单
     *
     * @param sellerId        卖家编号
     * @param detailsOrderIds 订单明细编号
     * @param state           订单使用状态
     * @return List<FiCbPaySettleOrderDo>  批次文件明细
     */
    List<ExternalOrderDo> selectBySellerId(@Param("sellerId") String sellerId,
                                           @Param("detailsOrderIds") List<Long> detailsOrderIds,
                                           @Param("state") Integer state);

    /**
     * 查询用户可用订单总金额
     *
     * @param sellerId 卖家编号
     * @return 成功总金额
     */
    BigDecimal sumExternalOrderAmt(@Param("sellerId") String sellerId);

    /**
     * 根据订单号批量修改订单的使用状态
     *
     * @param orderId  用户订单号
     * @param state    订单使用状态
     * @param userNo   用户号
     * @return 影响行数
     */
    int batchUpdateExternalOrder(@Param("orderIdList") List<String> orderId,
                                 @Param("state") Integer state,
                                 @Param("userNo") Long userNo);
}