package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.SysSecrueqaInfoDo;

import java.util.List;

public interface SysSecrueqaInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_SECRUEQA_INFO
     *
     * @mbg.generated
     */
    int insert(SysSecrueqaInfoDo record);

    /**
     * 查询系统安全问题
     *
     * @return 结果集
     */
    List<SysSecrueqaInfoDo> selectSysSecrueqaInfoList();

    /**
     * 根据问题编号查询系统安全问题信息
     *
     * @param questionNo 问题编号
     * @return 结果集
     */
    SysSecrueqaInfoDo selectSysSecrueqaInfoByQuestionNo(long questionNo);
}