package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.UserQuestionDo;
import com.baofu.international.global.account.core.dal.model.UserSecrueqaInfoDo;

import java.util.List;

public interface UserSecrueqaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_SECRUEQA_INFO
     *
     * @mbg.generated
     */
    UserSecrueqaInfoDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_SECRUEQA_INFO
     *
     * @mbg.generated
     */
    int insert(UserSecrueqaInfoDo record);

    /**
     * 新增用户安全问题
     *
     * @param userSecrueqaInfoDo 请求参数
     * @return 结果集
     */
    int insertInfo(UserSecrueqaInfoDo userSecrueqaInfoDo);


    /**
     * 获取用户安全问题信息
     *
     * @param userSecrueqaInfoDo 参数
     * @return List<UserSecrueqaInfoDo> 用户安全信息集合
     */
    List<UserQuestionDo> selectByQuestionNo(UserSecrueqaInfoDo userSecrueqaInfoDo);

    /**
     * 更新安全答案信息
     *
     * @param userSecrueqaInfoDo 参数
     * @return int
     */
    int updatedByQuestionNo(UserSecrueqaInfoDo userSecrueqaInfoDo);

    /**
     * 根据用户号查询用户密保问题
     *
     * @param userNo
     * @return
     */
    UserSecrueqaInfoDo selectByUserNo(Long userNo);

    /**
     * 删除安全问题
     */
    int deleteByUserNo(Long userNo);
}