package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.UserBankCardInfoDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 *
 */
public interface UserBankCardInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_BANK_CARD_INFO
     *
     * @mbg.generated
     */
    int insert(UserBankCardInfoDo userBankCardInfoDo);

    /**
     * 根据userNo查询出银行卡信息
     *
     * @param userNo userNo
     * @return
     */
    List<UserBankCardInfoDo> selectUserBankCardByUserNo(Long userNo);

    /**
     * 根据银行卡号查询出银行卡信息
     *
     * @param userNo   userNo
     * @param recordNo 记录编号
     * @return 返回银行卡信息
     */
    UserBankCardInfoDo selectUserBankCardNo(@Param("userNo") Long userNo, @Param("recordNo") Long recordNo);

    /**
     * 根据银行卡号删除银行卡信息
     *
     * @param userNo   userNo
     * @param recordNo 记录编号
     * @return
     */
    int delByUserBankCardNo(@Param("userNo") Long userNo, @Param("recordNo") Long recordNo);

    /**
     * 更新银行卡信息(若人工审核失败更新银行卡信息为失效)
     *
     * @param userNo 会员号
     * @return 更新记录数
     */
    Integer updateBankCartState(@Param("userNo") Long userNo, @Param("state") int state, @Param("updateBy") String updateBy);
}