package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.UserInfoDo;
import com.baofu.international.global.account.core.dal.model.user.UserQualifiedReqDo;
import com.baofu.international.global.account.core.dal.model.user.UserQualifiedRespDo;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbg.generated
     */
    UserInfoDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbg.generated
     */
    UserInfoDo selectByApplyNo(Long userInfoNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_INFO
     *
     * @mbg.generated
     */
    int insert(UserInfoDo record);

    /**
     * 根据用户号查询用户
     *
     * @param userNo 　用户号
     * @return　TUserInfoDo
     */
    UserInfoDo selectByUserNo(Long userNo);

    /**
     * 根据用户选择的信息筛选用户资质信息记录数
     *
     * @param userQualifiedReqDo 信息Do
     * @return 返回笔数
     */
    int countAllByCondition(UserQualifiedReqDo userQualifiedReqDo);

    /**
     * 根据用户选择的信息筛选用户资质信息
     *
     * @param userQualifiedReqDo 信息Do
     * @return 用户信息
     */
    List<UserQualifiedRespDo> selectAllByCondition(UserQualifiedReqDo userQualifiedReqDo);
}