package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.UserAccountBalDo;
import org.apache.ibatis.annotations.Param;

public interface UserAccountBalMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ACCOUNT_BAL
     *
     * @mbg.generated
     */
    int insert(UserAccountBalDo record);


    /**
     * 查询账户余额
     * 根据用户号、账户号查询
     *
     * @param accountNo 账户编号
     * @return 返回账户余额
     */
    UserAccountBalDo selectBalByAccNo(@Param("accountNo") Long accountNo, @Param("userNo") Long useNo);

    /**
     * 更新用户余额
     *
     * @param userAccountBalDo 账户余额信息
     * @return 返回受影响的行数
     */
    int updateAccountBal(UserAccountBalDo userAccountBalDo);
}