package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.UserLoginInfoDo;

import java.util.List;

public interface UserLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_LOGIN_INFO
     *
     * @mbg.generated
     */
    UserLoginInfoDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_LOGIN_INFO
     *
     * @mbg.generated
     */
    int insert(UserLoginInfoDo record);

    /**
     * 根据登录号查询
     *
     * @param loginNo 登录号码
     * @return 登录信息
     */
    UserLoginInfoDo findByLoginNo(String loginNo);

    /**
     * 根据loginNo查询记录条数
     *
     * @param loginNo 登录账户号(手机号或邮箱)
     * @return 结果集
     */
    int selectUseLoginInfoNum(String loginNo);

    /**
     * 新增用户登录信息
     *
     * @param userLoginInfoDo 请求参数
     * @return 结果集
     */
    int insertInfo(UserLoginInfoDo userLoginInfoDo);


    /**
     * 更新用户信息表 手机号
     *
     * @param userLoginInfoDo userLoginInfoDo
     * @return
     */
    int updateByUserNo(UserLoginInfoDo userLoginInfoDo);

    /**
     * 根据用户号查询用户注册手机号信息
     *
     * @param userNo 用户号
     * @return UserLoginInfoDo
     */
    UserLoginInfoDo queryUserInfoByUserNo(Long userNo);

    /**
     * 根据用户号查询用户登录信息
     *
     * @param userNo 用户号
     * @return UserLoginInfoDo
     */
    List<UserLoginInfoDo> queryUserInfoListByUserNo(Long userNo);

    /**
     * 根据用户号查询用户注册手机号信息
     *
     * @param userLoginInfoDo 用户号
     * @return UserLoginInfoDo
     */
    UserLoginInfoDo queryUserInfo(UserLoginInfoDo userLoginInfoDo);

}