package com.baofu.international.global.account.core.dal.mapper;


import com.baofu.international.global.account.core.dal.model.UserWithdrawDistributeDo;
import com.baofu.international.global.account.core.dal.model.WithdrawDetailsQueryDo;
import com.baofu.international.global.account.core.dal.model.WithdrawDistributeDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserWithdrawDistributeMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_WITHDRAW_DISTRIBUTE
     *
     * @mbg.generated
     */
    int insert(UserWithdrawDistributeDo userWithdrawDistributeDo);

    /**
     * 提现下发明细查询
     *
     * @param reqQuery req
     * @return List
     */
    List<WithdrawDistributeDo> selectWithdrawDistribute(WithdrawDetailsQueryDo reqQuery);

    /**
     * 根据订单号查询提现下发明细
     *
     * @param orderId 下发订单号
     * @return List
     */
    UserWithdrawDistributeDo selectDistributeByOrder(@Param("orderId") Long orderId);
}
