package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.UserLoginLogDo;

public interface UserLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_LOGIN_LOG
     *
     * @mbg.generated
     */
    UserLoginLogDo selectByKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_LOGIN_LOG
     *
     * @mbg.generated
     */
    int insert(UserLoginLogDo record);

    /**
     * 更新用户登录日志记录表
     *
     * @param userLoginLogDo 更新对象
     */
    int updateByUserNo(UserLoginLogDo userLoginLogDo);
}