package com.baofu.international.global.account.core.dal.mapper;

import com.baofu.international.global.account.core.dal.model.WithdrawOrderItemDo;

import java.util.List;

public interface WithdrawOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_WITHDRAW_ORDER_ITEM
     *
     * @mbg.generated
     */
    WithdrawOrderItemDo selectByKey(Long id);

    /**
     * 批量添加网关订单商品信息
     *
     * @param fiCbPayOrderItemDoList 网关订单商品信息
     * @return 返回受影响行数
     */
    int batchInsert(List<WithdrawOrderItemDo> fiCbPayOrderItemDoList);
}