package com.baofu.cbpayservice.dal.mapper;

import com.baofu.cbpayservice.dal.models.FiCbpayRemitConfigDo;

public interface FiCbpayRemitConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_CBPAY_REMIT_CONFIG
     *
     * @mbg.generated
     */
    FiCbpayRemitConfigDo selectByKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FI_CBPAY_REMIT_CONFIG
     *
     * @mbg.generated
     */
    int insert(FiCbpayRemitConfigDo record);
}