package com.baofu.cbpayservice.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 国家中英映射枚举类
 * <p>
 * Created by 莫小阳 on 2017/7/21.
 */

@Getter
@AllArgsConstructor
public enum CountryEnum {

    BTN("BTN", "不丹王国"),
    TMP("TMP", "东帝汶"),
    CHN("CHN", "中华人民共和国"),
    CAF("CAF", "中非共和国"),
    DNK("DNK", "丹麦王国"),
    UKR("UKR", "乌克兰"),
    UZB("UZB", "乌兹别克斯坦共和国"),
    UGA("UGA", "乌干达共和国"),
    URY("URY", "乌拉圭东岸共和国"),
    TCD("TCD", "乍得共和国"),
    YEM("YEM", "也门共和国"),
    ARM("ARM", "亚美尼亚共和国"),
    ISR("ISR", "以色列国"),
    IRQ("IRQ", "伊拉克共和国"),
    IRN("IRN", "伊朗伊斯兰共和国"),
    BLZ("BLZ", "伯利兹"),
    CPV("CPV", "佛得角共和国"),
    RUS("RUS", "俄罗斯联邦"),
    BGR("BGR", "保加利亚共和国"),
    HRV("HRV", "克罗地亚共和国"),
    GUM("GUM", "关岛"),
    GMB("GMB", "冈比亚共和国"),
    ISL("ISL", "冰岛共和国"),
    GIN("GIN", "几内亚共和国"),
    GNB("GNB", "几内亚比绍"),
    LIE("LIE", "列支敦士登公国"),
    COG("COG", "刚果共和国"),
    LBY("LBY", "大阿拉伯利比亚人民社会主义民众国"),
    LBR("LBR", "利比里亚共和国"),
    CAN("CAN", "加拿大"),
    GHA("GHA", "加纳共和国"),
    GAB("GAB", "加蓬共和国"),
    HUN("HUN", "匈牙利共和国"),
    MNP("MNP", "北马里亚纳自由联邦"),
    SGS("SGS", "南乔治岛和南桑德韦奇岛"),
    YUG("YUG", "南斯拉夫联盟共和国"),
    ATA("ATA", "南极洲"),
    ZAF("ZAF", "南非共和国"),
    BWA("BWA", "博茨瓦纳共和国"),
    QAT("QAT", "卡塔尔国"),
    RWA("RWA", "卢旺达共和国"),
    LUX("LUX", "卢森堡大公国"),
    IND("IND", "印度共和国"),
    IDN("IDN", "印度尼西亚共和国"),
    GTM("GTM", "危地马拉共和国"),
    ECU("ECU", "厄瓜多尔共和国"),
    ERI("ERI", "厄立特里亚国"),
    SYR("SYR", "阿拉伯叙利亚共和国"),
    CUB("CUB", "古巴共和国"),
    TWN("TWN", "中国台湾"),
    KGZ("KGZ", "吉尔吉斯共和国"),
    DJI("DJI", "吉布提共和国"),
    KAZ("KAZ", "哈萨克斯坦共和国"),
    COL("COL", "哥伦比亚共和国"),
    CRI("CRI", "哥斯达黎加共和国"),
    CMR("CMR", "喀麦隆共和国"),
    TUV("TUV", "图瓦卢"),
    TKM("TKM", "土库曼斯坦"),
    TUR("TUR", "土耳其共和国"),
    LCA("LCA", "圣卢西亚"),
    KNA("KNA", "圣基茨和尼维斯联邦"),
    STP("STP", "圣多美和普林西比民主共和国"),
    VCT("VCT", "圣文森特和格林纳丁斯"),
    SPM("SPM", "圣皮埃尔和密克隆"),
    CXR("CXR", "圣诞岛"),
    SHN("SHN", "圣赫勒拿"),
    SMR("SMR", "圣马力诺共和国"),
    GUY("GUY", "圭亚那合作共和国"),
    TZA("TZA", "坦桑尼亚联合共和国"),
    EGY("EGY", "阿拉伯埃及共和国"),
    ETH("ETH", "埃塞俄比亚"),
    KIR("KIR", "基里巴斯共和国"),
    TJK("TJK", "塔吉克斯坦共和国"),
    SEN("SEN", "塞内加尔共和国"),
    SLE("SLE", "塞拉利昂共和国"),
    CYP("CYP", "塞浦路斯共和国"),
    SYC("SYC", "塞舌尔共和国"),
    MEX("MEX", "墨西哥合众国"),
    TGO("TGO", "多哥共和国"),
    DMA("DMA", "多米尼克联邦"),
    DOM("DOM", "多米尼加共和国"),
    AUT("AUT", "奥地利共和国"),
    VEN("VEN", "委内瑞拉共和国"),
    BGD("BGD", "孟加拉人民共和国"),
    AGO("AGO", "安哥拉共和国"),
    AIA("AIA", "安圭拉"),
    ATG("ATG", "安提瓜和巴布达"),
    AND("AND", "安道尔"),
    FSM("FSM", "密克罗尼西亚联邦"),
    NIC("NIC", "尼加拉瓜共和国"),
    NGA("NGA", "尼日利亚联邦共和国"),
    NER("NER", "尼日尔共和国"),
    NPL("NPL", "尼泊尔王国"),
    PST("PST", "巴勒斯坦国"),
    BHS("BHS", "巴哈马联邦"),
    PAK("PAK", "巴基斯坦伊斯兰共和国"),
    BRB("BRB", "巴巴多斯"),
    PNG("PNG", "巴布亚新几内亚独立国"),
    PRY("PRY", "巴拉圭共和国"),
    PAN("PAN", "巴拿马共和国"),
    BHR("BHR", "巴林国"),
    BRA("BRA", "巴西联邦共和国"),
    BFA("BFA", "布基纳法索"),
    BVT("BVT", "布维岛"),
    BDI("BDI", "布隆迪共和国"),
    GRC("GRC", "希腊共和国"),
    COK("COK", "库克群岛"),
    CYM("CYM", "开曼群岛"),
    DEU("DEU", "德意志联邦共和国"),
    ITA("ITA", "意大利共和国"),
    SLB("SLB", "所罗门群岛"),
    ZAR("ZAR", "扎伊尔共和国"),
    TKL("TKL", "托克劳"),
    LVA("LVA", "拉脱维亚共和国"),
    NOR("NOR", "挪威王国"),
    CZE("CZE", "捷克共和国"),
    MDA("MDA", "摩尔多瓦共和国"),
    MAR("MAR", "摩洛哥王国"),
    MCO("MCO", "摩纳哥公国"),
    BRN("BRN", "文莱达鲁萨兰国"),
    FJI("FJI", "斐济共和国"),
    SWZ("SWZ", "斯威士兰王国"),
    SVK("SVK", "斯洛伐克共和国"),
    SVN("SVN", "斯洛文尼亚共和国"),
    SJM("SJM", "斯瓦尔巴群岛"),
    LKA("LKA", "斯里兰卡民主社会主义共和国"),
    SGP("SGP", "新加坡共和国"),
    NCL("NCL", "新喀里多尼亚"),
    NZL("NZL", "新西兰"),
    JPN("JPN", "日本国"),
    CHL("CHL", "智利共和国"),
    PRK("PRK", "朝鲜民主主义人民共和国"),
    KHM("KHM", "柬埔寨王国"),
    GRD("GRD", "格林纳达"),
    GRL("GRL", "格陵兰"),
    GEO("GEO", "格鲁吉亚共和国"),
    VAT("VAT", "梵蒂冈城国"),
    BEL("BEL", "比利时王国"),
    MRT("MRT", "毛里塔尼亚伊斯兰共和国"),
    MUS("MUS", "毛里求斯共和国"),
    TON("TON", "汤加王国"),
    SAU("SAU", "沙特阿拉伯王国"),
    FRA("FRA", "法兰西共和国"),
    ATF("ATF", "法属南部领土"),
    GUF("GUF", "法属圭亚那"),
    PYF("PYF", "法属波利尼西亚"),
    FRO("FRO", "法罗群岛"),
    POL("POL", "波兰共和国"),
    PRI("PRI", "波多黎各自由联邦"),
    BIH("BIH", "波斯尼亚和黑塞哥维那共和国"),
    THA("THA", "泰王国"),
    ZWE("ZWE", "津巴布韦共和国"),
    HND("HND", "洪都拉斯共和国"),
    HTI("HTI", "海地共和国"),
    AUS("AUS", "澳大利亚联邦"),
    MAC("MAC", "澳门"),
    IRL("IRL", "爱尔兰"),
    EST("EST", "爱沙尼亚共和国"),
    JAM("JAM", "牙买加"),
    TCA("TCA", "特克斯和凯科斯群岛"),
    TTO("TTO", "特立尼达和多巴哥共和国"),
    BOL("BOL", "玻利维亚共和国"),
    NRU("NRU", "瑙鲁共和国"),
    SWE("SWE", "瑞典王国"),
    CHE("CHE", "瑞士联邦"),
    GLP("GLP", "瓜德罗普"),
    WLF("WLF", "瓦利斯和富图纳群岛"),
    VUT("VUT", "瓦努阿图共和国"),
    REU("REU", "留尼汪"),
    BLR("BLR", "白俄罗斯共和国"),
    BMU("BMU", "百慕大群岛"),
    PCN("PCN", "皮特凯恩岛"),
    GIB("GIB", "直布罗陀"),
    KWT("KWT", "科威特国"),
    COM("COM", "科摩罗伊斯兰联邦共和国"),
    CCK("CCK", "科科斯(基林)群岛"),
    PER("PER", "秘鲁共和国"),
    TUN("TUN", "突尼斯共和国"),
    LTU("LTU", "立陶宛共和国"),
    SOM("SOM", "索马里共和国"),
    JOR("JOR", "约旦哈希姆王国"),
    NAM("NAM", "纳米比亚共和国"),
    NIU("NIU", "纽埃"),
    MMR("MMR", "缅甸联邦"),
    ROM("ROM", "罗马尼亚"),
    USA("USA", "美利坚合众国"),
    UMI("UMI", "美属太平洋各群岛"),
    VIR("VIR", "美属维尔京群岛"),
    ASM("ASM", "美属萨摩亚"),
    KEN("KEN", "肯尼亚共和国"),
    FIN("FIN", "芬兰共和国"),
    SDN("SDN", "苏丹共和国"),
    SUR("SUR", "苏里南共和国"),
    GBR("GBR", "大不列颠及北爱尔兰联合王国"),
    IOT("IOT", "英属印度洋领土"),
    VGB("VGB", "英属维尔京群岛"),
    NLD("NLD", "荷兰王国"),
    ANT("ANT", "荷属安的列斯"),
    MOZ("MOZ", "莫桑比克共和国"),
    LSO("LSO", "莱索托王国"),
    PHL("PHL", "菲律宾共和国"),
    SLV("SLV", "萨尔多瓦共和国"),
    PRT("PRT", "葡萄牙共和国"),
    MNG("MNG", "蒙古国"),
    MSR("MSR", "蒙特塞拉特"),
    ESH("ESH", "西撒哈拉"),
    ESP("ESP", "西班牙"),
    WSM("WSM", "西萨摩亚独立国"),
    NFK("NFK", "诺福克岛"),
    PLW("PLW", "贝劳共和国"),
    BEN("BEN", "贝宁共和国"),
    ZMB("ZMB", "赞比亚共和国"),
    GNQ("GNQ", "赤道几内亚共和国"),
    HMD("HMD", "赫德岛和麦克唐纳岛"),
    VNM("VNM", "越南社会主义共和国"),
    AZE("AZE", "阿塞拜疆共和国"),
    AFG("AFG", "阿富汗伊斯兰国"),
    DZA("DZA", "阿尔及利亚民主人民共和国"),
    ALB("ALB", "阿尔巴尼亚共和国"),
    OMN("OMN", "阿曼苏丹国"),
    ARG("ARG", "阿根廷共和国"),
    ARE("ARE", "阿拉伯联合酋长国"),
    ABW("ABW", "阿鲁巴"),
    KOR("KOR", "大韩民国"),
    HKG("HKG", "香港"),
    MKD("MKD", "马其顿共和国"),
    MDV("MDV", "马尔代夫共和国"),
    FLK("FLK", "马尔维纳斯群岛"),
    MWI("MWI", "马拉维共和国"),
    MTQ("MTQ", "马提尼克"),
    MYS("MYS", "马来西亚"),
    MYT("MYT", "马约特"),
    MHL("MHL", "马绍尔群岛共和国"),
    MLT("MLT", "马耳他共和国"),
    MDG("MDG", "马达加斯加共和国"),
    MLI("MLI", "马里共和国"),
    LBN("LBN", "黎巴嫩共和国");


    /**
     * 国家简称
     */
    private String key;

    /**
     * 国家中文
     */
    private String value;

    public static String getCountryCHN(String key) {
        for (CountryEnum enums : values()) {
            if (key.equals(enums.getKey())) {
                return enums.getValue();
            }
        }
        return null;
    }

}
